import "./globals.css";
import type { Metadata } from "next";
import ThemeRegistry from "./provider/ThemeRegistry";
import { Inter } from "next/font/google";

const interFont = Inter({
  subsets: ["latin"],
  style: ["normal"],
  weight: ["400", "600", "800"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={interFont.className}>
        <ThemeRegistry options={{ key: "mui" }}>{children}</ThemeRegistry>
      </body>
    </html>
  );
}
