import "./globals.css";
import type { Metadata } from "next";
import { Ubuntu } from "next/font/google";
import ThemeRegistry from "./provider/ThemeRegistry";

const ubuntuFont = Ubuntu({
  subsets: ["latin", "cyrillic"],
  style: ["normal"],
  weight: ["300", "400", "500", "700"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={ubuntuFont.className}>
        <ThemeRegistry options={{ key: "mui" }}>{children}</ThemeRegistry>
      </body>
    </html>
  );
}
